#!/bin/bash

#Set local environment variables
export SFEMaNS_DIR=/Users/eric/shallow-water-eric/SFEMaNS
#Declare files
file_in=dummy_file
file_out=makefile
if [ -f $file_out ]; then
   rm $file_out
fi

#Create dummy_file
./fmkmf.sh -p .:$SFEMaNS_DIR/FEMSUB:$SFEMaNS_DIR/FEMSUB_OBJET:$SFEMaNS_DIR/GAUSS_POINTS_OBJET main.f90 > $file_in

echo $file_in 'done'

#Create makefile
ok=0
while read line
do
   if [ "$line" == "F90=f90" ]; then
      ok=1
   fi
   if ((ok==1)); then
      echo "$line" >> $file_out
   fi
done < $file_in

rm -rf $file_in
echo $file_in 'removed'

#Edit file # on Macs install gnu-sed with default names using homebrew
sed -i 's/main:/a.exe:/g' $file_out
sed -i 's/main /a.exe /g' $file_out
sed -i 's/clean/cl/g' $file_out
sed -i '1s/F90=f90/include make.inc/' $file_out
#sed -i '4s/sub_plot.o/sub_plot.o -L$(LIB_PARDISO)/' $file_out
#sed -i '68s/solver_pardiso.f90/solver_pardiso.f90 -I$(INC_PARDISO)/'  $file_out
sed -i '$s/rm/\t rm/' $file_out
sed -i 's/$(F90)/\t$(F90)/g' $file_out
sed -i '4s/F90/LNK/' $file_out

#Take care of $SFEMaNS_DIR and /////
replacement=$SFEMaNS_DIR
echo $replacement > tt
sed -i 's/\//@@/g' tt
read replacement  < tt
rm -rf tt

sed -i 's/\//@@/g' $file_out
sed -i "s/${replacement}/\$(ROOT)/g" $file_out
sed -i 's/@@/\//g' $file_out

echo $file_out 'done'
