#!/bin/bash
# @ job_name = MHD_interp_neg
# @ job_type = parallel
# @ output = MHD_interp_neg_cyl20.out
# @ error = MHD_interp_neg_cyl20.err
# @ cpu_limit = 0:55:00
# @ job_cpu_limit = 01:00:00
# @ data_limit = 1.3gb
# @ total_tasks = 1
# @ queue
# Pour avoir l'écho des commandes
set -x
## DIRECTORIES DE SAUVEGARDE
## GAYADIR = SAVE SUR GAYA
## GAYAGET = GET SUR GAYA
## WORK    = SAVE SUR SWORKDIR
#export GAYADIR=RESULTATS/MHD/TC_ANTI_Re120/CYL20_TCM_DEMI_Z_UNIF/Rm240/essai_interp
#export GAYAGET=RESULTATS/MHD/TC_ANTI_Re120/CYL20_TCM_DEMI_Z_UNIF/Rm240/tfin_1400
export GAYADIR=RESULTATS/MHD/TC/Re_120_Rm_195/CYL20_SYM/HP2_PhiP2/RESTART_TC_VP/restart_neg_tfin_8400
export GAYAGET=RESULTATS/MHD/TC/Re_120_Rm_195/CYL20_SYM/HP2_PhiP2/RESTART_TC_VP/tfin_8400
export GAYAGETMESH=RESULTATS/MAILLAGES_TC
export GAYAGETMH=RESULTATS/MAILLAGES_TC
export WORK=$WORKDIR/RL/TCMHD/Re_120_Rm_195/CYL20_SYM/HP2_PhiP2/RESTART_TC_VP/restart_neg
mkdir $WORK
##
# Répertoire temporaire de travail
cd $TMPDIR
# La variable LOADL_STEP_INITDIR est automatiquement positionnée par 
# LoadLeveler au répertoire dans lequel on tape la commande llsubmit
cp $LOADL_STEP_INITDIR/interpol_neg.exe interpol_neg.exe 
#cp $LOADL_STEP_INITDIR/interpol_mono.exe interpol_mono.exe 
mfget $GAYAGETMH/CYL20_TCM_SYM_Z.FEM CYL20_TCM_SYM_Z.FEM
cp $LOADL_STEP_INITDIR/data_interpol_neg data_interpol_neg
## GET SUR GAYA
mfget $GAYAGET/suite_maxwell_012.CYL20_TCM_SYM_Z.FEM suite_maxwell.CYL20_TCM_SYM_Z.FEM
# Exécution d'un programme MPI
./interpol_neg.exe
#./interpol_mono.exe
ls -lrt
cp suite*999*  $WORK
mfput suite*999* $GAYADIR
