#!/usr/bin/bash
# by Katarzyna Boronska
# July 2007

usage="This script interactively runs a job prepared for the LoadLleveler. \
Use it for short-time computations. \
Before submitting it verifies that \
the job_name is the same as the current directory name \
and that no results with the same name are already on gaya."

if [[ $# -lt 1 ]] ; then
	echo $usage
	exit 1
fi

job=$1

curdir=$PWD
correctname=${curdir##*/}

# check the name:
jobname=$(perl -ne '/\# \@ job_name\s*=\s*(\S+)/ and do { print $1; exit } ' $job)
tasks=$(perl -ne '/\# \@ total_tasks\s*=\s*(\S+)/ and do { print $1; exit } ' $job)

if [[ $jobname != $correctname ]] ; then
	echo "Error! The job name is ${jobname}, but the directory is $correctname!"
	echo "The job will not be submitted." 
	exit 2
fi

lsresult=$(rsh gaya ls results/$jobname 2>&1)
if [[ $lsresult != *ERROR* ]] ; then
	echo "Error! results/$jobname exists already on gaya!"
	echo "The job will not be submitted."
	exit 3
fi

# If everything went fine, we submit the job

# set the variables for interactive use  
export LOADL_STEP_INITDIR=$PWD
export LOADL_JOB_NAME=$jobname
export MP_PROCS=$tasks
export TMPDIR=$WORKDIR/${jobname}_tmp

./${job}

# if everything went fine, remove the job file
if [[ $? -eq 0 ]] ; then
	rm .${job}_int
fi

